//$file${.::../Inc::terminal.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: addon.qm
// File:  ${.::../Inc::terminal.hpp}
//
// This code has been generated by QM 7.0.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::../Inc::terminal.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef TERMINAL_HPP_
#define TERMINAL_HPP_

//$declare${BaseShared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${BaseShared::AppSignals} ..................................................
enum AppSignals : QP::QSignal {
    TIMEOUT_SIG = QP::Q_USER_SIG, // posted by time event
    ADDON_LAST_SIG,
};

//${BaseShared::AO_Terminal} .................................................
extern QP::QActive * const AO_Terminal;

} // namespace APP
//$enddecl${BaseShared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${BaseAOs::Terminal} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${BaseAOs::Terminal} .......................................................
class Terminal : public QP::QActive {
public:
    static Terminal inst;

private:
    QP::QTimeEvt m_timeEvt;

public:
    bool m_gotReply;
    char m_input[20];
    std::uint8_t m_replySize;
    bool m_gotChar;
    std::uint8_t m_maxInputSize;

public:
    Terminal();
    virtual void DispatchCommand(char command);

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(start);
    Q_STATE_DECL(receiveUserReply);
    Q_STATE_DECL(receivingNextChar);
    Q_STATE_DECL(sendUserPrompt);
}; // class Terminal

} // namespace APP
//$enddecl${BaseAOs::Terminal} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // DPP_HPP_
